#!/usr/bin/perl
system('2>/dev/null 1>&2 chromium-browser --start-fullscreen /home/pi/projects/PiDash/html/index.html &');
system('sh /home/pi/projects/PiDash/refresh.sh');
my $blanked = 0;
open (IN, "xscreensaver-command -watch |");
while (<IN>) {
    if (m/^BLANK/) {
        if (!$blanked) {
	    system "echo -n Blanking screen at:";
            system "date";
            $blanked = 1;
        }
    } elsif (m/^UNBLANK/) {
	system "echo -n Un-Blanking screen at:";
	system "date";
        system "sh /home/pi/projects/PiDash/refresh.sh";
        $blanked = 0;
    }
}